---
name: "Lint project"

on:
  pull_request:
    branches: ["develop"]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  docker:
    name: Lint dockerfile ğŸŸ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        with:
          dockerfile: Dockerfile
      - name: Build dockerfile
        run: docker build . -t service
  pr:
    name: Validate PR title ğŸ˜“
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignoreLabels: |
            bot
            autorelease: pending
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey mate ğŸ‘‹. Thank you for opening this Pull Request ğŸ¤˜. It is really awesome to see this contribution ğŸš€

            ğŸ” When working with this project we are requesting to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted ğŸ¥¶.

            ğŸ‘‡ Bellow you can find details about what failed:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
  dotenv:
    name: Lint dotenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dotenv
        run: curl -sSfL https://git.io/JLbXn | sh -s -- -b usr/local/bin v3.3.0

      - name: Run dotenv
        run: usr/local/bin/dotenv-linter
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.26
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
  yamlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint .
